require('core.plugin_config.gruvbox')
require('core.plugin_config.lualine')
require('core.plugin_config.nvim-tree')
require('core.plugin_config.telescope')
require('core.plugin_config.nvim-treesitter')
require('core.plugin_config.lsp_config')
require('core.plugin_config.completions')
require('core.plugin_config.nvim-autopairs')
require('core.plugin_config.comment')
require('core.plugin_config.test')
require('core.plugin_config.dap')
require('core.plugin_config.noice')

